# Loss
criterion: TripletLoss
criterion_kwargs:
   margin: 0.8

# Model
backbone: resnet18
fc_layer_size: 128

# Dataset
train_db_name: LFW
train_split: train
test_db_name: LFWPairs
test_split: 10fold

# Transformations
# augmentation_strategy: ours 
# augmentation_kwargs:
#    crop_size: 96
#    normalize:
#       mean: [0.485, 0.456, 0.406]
#       std: [0.229, 0.224, 0.225]
#    num_strong_augs: 4
#    cutout_kwargs:
#      n_holes: 1
#      length: 32
#      random: True

transformation_kwargs:
   crop_size: [128, 98]
   resize: 224
   normalize:
      mean: [0.5929, 0.4496, 0.3654]
      std: [0.2287, 0.1959, 0.1876]

# Hyperparameters
optimizer: adamw
optimizer_kwargs:
   lr: 0.005

epochs: 500
batch_size: 256
num_workers: 2

# Scheduler
scheduler: onecyclelr
scheduler_kwargs:
  max_lr: 0.005
  min_lr: 0.000005